<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="contentscomposer"
    nsURI="http://www.roboidstudio.org/model/contentscomposer" nsPrefix="org.roboid.studio.contentscomposer">
  <eClassifiers xsi:type="ecore:EClass" name="ContentsComposerElement" abstract="true">
    <eOperations name="addPropertyChangeListener">
      <eParameters name="listener" eType="ecore:EDataType ../../org.roboid.studio.timeline.model/model/timeline.ecore#//PropertyChangeListener"/>
    </eOperations>
    <eOperations name="firePropertyChange">
      <eParameters name="propertyName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="oldValue" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      <eParameters name="newValue" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eOperations>
    <eOperations name="removePropertyChangeListener">
      <eParameters name="listener" eType="ecore:EDataType ../../org.roboid.studio.timeline.model/model/timeline.ecore#//PropertyChangeListener"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MotionContent" eSuperTypes="#//ContentsComposerElement #//IClip">
    <eOperations name="addChild">
      <eParameters name="child" eType="#//BlockElement"/>
    </eOperations>
    <eOperations name="removeChild">
      <eParameters name="child" eType="#//BlockElement"/>
    </eOperations>
    <eOperations name="validate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="getDeviceNames" eType="#//StringArray"/>
    <eOperations name="getActiveDeviceNames" eType="#//StringArray"/>
    <eOperations name="reset"/>
    <eOperations name="createScriptEngine" eType="#//ScriptEngine"/>
    <eOperations name="getDevices" upperBound="-1" eType="ecore:EClass platform:/plugin/org.roboid.robot.model/model/robot.ecore#//Device"/>
    <eOperations name="getMotionClipBlocks" upperBound="-1" eType="#//MotionClipBlock"/>
    <eOperations name="getMotionContentBlocks" upperBound="-1" eType="#//MotionContentBlock"/>
    <eOperations name="addAssociation">
      <eParameters name="association" eType="#//Association"/>
    </eOperations>
    <eOperations name="removeAssociation">
      <eParameters name="association" eType="#//Association"/>
    </eOperations>
    <eOperations name="getDeviceName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eParameters name="index" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eOperations name="getDevice" eType="ecore:EClass platform:/plugin/org.roboid.robot.model/model/robot.ecore#//Device">
      <eParameters name="index" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eOperations name="findMotionClipBlock" eType="#//MotionClipBlock">
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="findMotionContentBlock" eType="#//MotionContentBlock">
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="deepCopy" eType="#//MotionContent"/>
    <eOperations name="refreshResource"/>
    <eOperations name="refreshResource">
      <eParameters name="uri" eType="ecore:EDataType ../../org.roboid.studio.timeline.model/model/timeline.ecore#//URI"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="robot" eType="ecore:EClass platform:/plugin/org.roboid.robot.model/model/robot.ecore#//Robot"
        transient="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activity" eType="ecore:EClass ../../org.roboid.core.component.activity/model/activity.ecore#//Activity"
        transient="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scriptEngine" eType="#//ScriptEngine"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="blocks" upperBound="-1"
        eType="#//BlockElement" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="grid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minimized" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="terminatorScriptCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="associations" upperBound="-1"
        eType="#//Association" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="1.0.0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MovableElement" abstract="true" eSuperTypes="#//ContentsComposerElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Association" eSuperTypes="#//ContentsComposerElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//BlockElement"
        resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//BlockElement"
        resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourceLabel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetLabel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BlockElement" abstract="true" eSuperTypes="#//MovableElement">
    <eOperations name="canHaveScript" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="updateScript">
      <eParameters name="scriptName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="scriptCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getLabel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eOperations name="canDelete" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="canCopy" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="canCut" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="addIncoming">
      <eParameters name="association" eType="#//Association"/>
    </eOperations>
    <eOperations name="addOutgoing">
      <eParameters name="association" eType="#//Association"/>
    </eOperations>
    <eOperations name="removeIncoming">
      <eParameters name="association" eType="#//Association"/>
    </eOperations>
    <eOperations name="removeOutgoing">
      <eParameters name="association" eType="#//Association"/>
    </eOperations>
    <eOperations name="getVariable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eOperations name="reset"/>
    <eOperations name="canReconnect" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="newSource" eType="#//BlockElement"/>
      <eParameters name="newTarget" eType="#//BlockElement"/>
      <eParameters name="oldBlock" eType="#//BlockElement"/>
    </eOperations>
    <eOperations name="validate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="canConnect" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="source" eType="#//BlockElement"/>
      <eParameters name="target" eType="#//BlockElement"/>
    </eOperations>
    <eOperations name="deepCopy" eType="#//BlockElement">
      <eParameters name="newParent" eType="#//MotionContent"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="error" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="playing" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incomings" upperBound="-1"
        eType="#//Association" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoings" upperBound="-1"
        eType="#//Association" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scriptType" eType="#//ScriptType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scriptName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scriptCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nextBlock" eType="#//BlockElement"
        changeable="false" volatile="true" transient="true" derived="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//MotionContent"
        transient="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RootBlock" eSuperTypes="#//BlockElement">
    <eOperations name="executeScript"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TerminatorBlock" eSuperTypes="#//BlockElement">
    <eOperations name="copyScriptType"/>
    <eOperations name="executeScript"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AdderBlock" eSuperTypes="#//BlockElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiceBlock" eSuperTypes="#//BlockElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="range" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LoopBlock" eSuperTypes="#//BlockElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="count" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="yesBlock" eType="#//BlockElement"
        changeable="false" volatile="true" transient="true" derived="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="noBlock" eType="#//BlockElement"
        changeable="false" volatile="true" transient="true" derived="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ForkBlock" eSuperTypes="#//BlockElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="MergeBlock" eSuperTypes="#//BlockElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="LogicBlock" abstract="true" eSuperTypes="#//BlockElement">
    <eOperations name="checkCondition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="frame" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="logic" eType="#//LogicType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="index" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="device" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BranchBlock" eSuperTypes="#//LogicBlock">
    <eStructuralFeatures xsi:type="ecore:EReference" name="yesBlock" eType="#//BlockElement"
        changeable="false" volatile="true" transient="true" derived="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="noBlock" eType="#//BlockElement"
        changeable="false" volatile="true" transient="true" derived="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TriggerBlock" eSuperTypes="#//LogicBlock"/>
  <eClassifiers xsi:type="ecore:EClass" name="ClipBlock" abstract="true" eSuperTypes="#//BlockElement">
    <eOperations name="resetTriggers"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="frame" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClipBlockWithFrame" abstract="true"
      eSuperTypes="#//ClipBlock">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startFrame" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stopFrame" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MotionClipBlock" eSuperTypes="#//ClipBlockWithFrame">
    <eOperations name="getTotalFrames" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eOperations name="updateName">
      <eParameters name="newName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="countClones" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="motionClip" eType="ecore:EClass ../../org.roboid.studio.timeline.model/model/timeline.ecore#//MotionClip"
        containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MotionClipCloneBlock" eSuperTypes="#//ClipBlockWithFrame">
    <eOperations name="getTotalFrames" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="original" eType="#//MotionClipBlock"
        resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MotionContentBlock" eSuperTypes="#//ClipBlock">
    <eOperations name="updateName">
      <eParameters name="newName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="countClones" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="#//MotionContent"
        containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MotionContentCloneBlock" eSuperTypes="#//ClipBlock">
    <eStructuralFeatures xsi:type="ecore:EReference" name="original" eType="#//MotionContentBlock"
        resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WaitClipBlock" eSuperTypes="#//ClipBlockWithFrame">
    <eOperations name="checkTimeout" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="frame" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eOperations name="timeoutToString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeout" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        defaultValueLiteral="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ScriptType">
    <eLiterals name="None"/>
    <eLiterals name="RoboidScript" value="1" literal="Roboid Script"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LogicType">
    <eLiterals name="EQ" literal="=="/>
    <eLiterals name="NE" value="1" literal="!="/>
    <eLiterals name="GT" value="2" literal=">"/>
    <eLiterals name="GE" value="3" literal=">="/>
    <eLiterals name="LT" value="4" literal="&lt;"/>
    <eLiterals name="LE" value="5" literal="&lt;="/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Rectangle" instanceClassName="org.eclipse.draw2d.geometry.Rectangle"/>
  <eClassifiers xsi:type="ecore:EDataType" name="PropertyChangeListener" instanceClassName="java.beans.PropertyChangeListener"/>
  <eClassifiers xsi:type="ecore:EDataType" name="ScriptEngine" instanceClassName="javax.script.ScriptEngine"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Shell" instanceClassName="org.eclipse.swt.widgets.Shell"/>
  <eClassifiers xsi:type="ecore:EDataType" name="StringArray" instanceClassName="java.lang.String[]"/>
  <eClassifiers xsi:type="ecore:EClass" name="IClip" instanceClassName="org.roboid.core.runtime.IClip"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EDataType" name="URI" instanceClassName="org.eclipse.emf.common.util.URI"/>
</ecore:EPackage>
